Catkin-ProjectName: darc_examples
Description: 
Author: Morten Kjaergaard <mkjargaard@willowgarage.com>
Maintainer: Morten Kjaergaard <mkjargaard@willowgarage.com>
Homepage: 
Vcs-Git: 

Version: 0.0.1

Depends: darc

Catkin-CopyrightType: willowgarage
Catkin-DebRulesType: python_distutils
